### ISSUE TITLE
Add a quit behaviour to the Esc key

### ISSUE THREAD

**Issue by susnux** [KOBUGE-Games/jetpaca#13]
Hi,
Found this very nice little game, but there is one question:
When starting in fullscreen-mode (godot -f -path ...) how do I exit the game?
There is no menu with "Quit" or "Exit".
I know I can pause the game (the || button) then click the "back"-arrow, which will take be back in the world selection, but the arrow on the left (bottom) does not work (does nothing)).
Thank you

**Comment by akien-mga** [comment]
Good question, I guess Alt+F4 would work, but I'll check what Esc does. It should probably bring back to the menu and, when on the menu, exit.
