### ISSUE TITLE
Parallax Background Doesn't Fit the Screen at Certain Areas

### ISSUE THREAD

**Issue by ScotFlux** [KOBUGE-Games/jetpaca#14]
- Win 7, Win 10 x64
- Godot 2.0.4 or newer

=> Happened : In a certain areas (locations), Parallax background doesn't seem to behave correctly. Doesn't Fit the whole Screen. See right side of the Gif below : 
http://i.imgur.com/YCOA7JS.gif?1

=> Expected : It should fit the whole screen.

**Comment by akien-mga** [comment]
Thanks, I'm not sure why this happens but I'll investigate.

**Comment by akien-mga** [comment]
This is easily visible in the `introg` level, where the parallax is broken at the starting position:
![spectacle k28662](https://cloud.githubusercontent.com/assets/4701338/16902242/95d81440-4c59-11e6-8e92-e335a4af95cc.png)

It seems to happen when near the `x = 0` position, probably a weird interaction between the Camera2D and the ParallaxBackground.

**Comment by akien-mga** [comment]
I tested all parallax backgrounds in this level and it seems to happen with three of them:
- glacier_parallax.tscn (screenshot above)
- ocean_parallax.tscn
- temple_parallax.tscn

**Comment by bojidar-bg** [comment]
@akien-mga nice work, now we only have to check what is so different with them.

**Comment by bojidar-bg** [comment]
Heh, two-line fix in the scene file :wink:

**Comment by akien-mga** [comment]
:tada:

**Comment by ScotFlux** [comment]
Yeah, it works very well. :+1:
