### ISSUE TITLE
Port to Godot 2.0

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/jetpaca#2]
Opening the project as is in Godot 2.0 kind of works already, though by playing around I've noticed a few issues:
- some scenes seem to have lost some of their content, like enemies/explosion.xml
- some functions are missing so some levels won't load due to API breakage
- some tiles seems to have a bad offset, probably due to an engine bug that was recently fixed and was likely there from the beginning

All in all nothing too hard to handle, but we'll have to be cautious and do it right, especially so that we don't lose data. As the current code was seemingly developed on Godot pre-1.0, I propose the following:
- With Godot 1.0, open the project and check how it behaves. If it seems better, resave all scenes using Godot 1.0 to update their contents, and check the `git diff` for each file to ensure that no information is lost (like animations, etc.)
- Do the same with Godot 1.1
- Do the same with Godot 2.0

Once all this scene format upgrade has been done, we can start considering actually fixing the API changes, tilesets and maybe port the scenes files to the TSCN format.

**Comment by punto-** [comment]
Is that necessary? I would say try opening them with 2.0 and replace the
missing assets.. Even if everything worked out of the box, it's likely that
most scenes will require assets to be changed or remade, so it's not worth
it to go through all those steps for every scene I think..

**Comment by akien-mga** [comment]
It might be overkill indeed, I'll try to experiment a bit more to see if we really lose data when using Godot 2.0 directly.

Actually it was when opening enemies/explosion.xml that I was under the impression that some metadata might be lost, as it doesn't _show_ anything out of the box in the editor. But by having another look right now I've noticed that all the visual and audio effects are triggered by calling the explode() function :)

I'll try to go directly with 2.0 then, and maybe just launch the original game with 1.0 just to compare and see if I spot regressions.

**Comment by akien-mga** [comment]
Fixed with #5 and later on with porting to TSCN. There were not as many issues as I had imagined in the end :)

**Comment by aaronfranke** [comment]
What about to 3.0? It would be nice if Jetpaca could serve as a "What Godot can do" demo game.

**Comment by akien-mga** [comment]
https://github.com/KOBUGE-Games/jetpaca/tree/godot-3-port
