### ISSUE TITLE
Resources that can't be converted to 2.0 format

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/jetpaca#4]
Related to #2.

There are a few resources which can't be converted to the tscn/tres format of Godot 2.0 right now, due to incompatibility with their current format or lack of their source.

Tilesets:
- [x] _Redone_ `cave_scene.xml` can't be opened in Godot 2.0 (nor in 1.0 or 1.1). The tileset resource could be converted to tres though, so it can be reverse-engineered.
- [x] `mountain_scene.xml`, same issue. The resource was also converted to tres.
- [x] `glacier_tileset.tres` has no associated source scene, so it should also be reverse-engineered.

Fonts: **Edit:** The fonts are nonfree, should be replaced.
- `art/font.xfnt`
- `art/font_big.xres`
  For those two the original fonts are not included in the source, so we'd need to find which font that was to reimport them.

PackedScenes:
- [x] `tilesets/alpaca_statue.xml`, no clue what it is but it doesn't load either.
- [x] `tilesets/mountain_moving_plat.xml`, same thing.

I'll try to build an early revision of Godot post-open sourcing to see how it handles those files.

**Comment by akien-mga** [comment]
Regarding the fonts, if @reduz or @punto- remember which fonts were used, it would be great. The current resource files work, but without means to adapt the to more recent formats, they might break one day, or we might get stuck wanting to use them at different sizes and not being able to :/

**Comment by punto-** [comment]
I see at least 2 fonts, ArmWrestler.ttf and BPdiet.otf

Somewhat related: is it a good idea to have the engine.cfg at the root of
the repository? We have a bunch of source files like psd, ttf, xcf (I think
those have tilesets), there's even some ps vita project files (we can't
publish those :p), but those should all go outside the game directory, and
as you say it's a good idea to have them in case we want to re-export the
fonts, etc. Usually the structure would be something like:

art/ (for the ttf, psd, etc)
doc/ (this might be on the wiki tho)
tools/ (for misc scripts and stuff like that)
game/ (engine.cfg is here)

Even if the bigger files can't go on git (since it's not very good with big
binary files), it's a good idea to have them somewhere..

**Comment by akien-mga** [comment]
> I see at least 2 fonts, ArmWrestler.ttf and BPdiet.otf

Thanks!

> Somewhat related: is it a good idea to have the engine.cfg at the root of the repository?

That's a good question. There are two alternatives, either move the engine.cfg and the related game stuff to a game/ folder, or move all resources not used directly in-game to their own git repo (I started using this for one of my early games https://github.com/akien-mga/dynadungeons-assets-source, though I'll admit I still have files locally that I haven't pushed to this git repo yet, should take the time to do it :D).

The advantage of the former is that the git repo contains everything, so developers just have to clone one repo and each time they change a source asset they share it directly. The drawback is that the repo history gets much bigger (which is why for example @reduz could not upload the whole git history for the game, as it was too heavy due to PSD files).

With the latter, the advantage is that the game repo stays lightweight, and players who are only interested in playing the game don't have to download all source files. The drawback is that you don't get everything in the same place, and my above example shows that sometimes devs might forget to version the asset sources they used in the separate git repo ;)

So all in all I like the two possibilities, for my games I've mostly used the second (two separate repos) but I'm open to trying the first one too. @KOBUGE-Games/bureaucrats, WDYT?

**Comment by bojidar-bg** [comment]
@akien-mga I'm for the second option, as this would mean you don't need to clone an additional 50MB to  edit the code

**Comment by fry-** [comment]
I also vote for the 2nd one. I think we can keep an eye on a separate repo and motivate each other to keep it updated^^

**Comment by bojidar-bg** [comment]
@akien-mga ~ Is this issue a blocker for level designing and coding?

**Comment by akien-mga** [comment]
I edited the OP to reflect the current status. All tilesets resources could be converted to TRES, but not all the corresponding scene files, so we'd have to recreate them (all the info is in the TRES, it could maybe be scripted :p).

The fonts are nonfree so should be replaced.

Still no clue about `tilesets/alpaca_statue.xml` and `tilesets/mountain_moving_plat.xml`.
